package com.company.dataanalytics.domain.repositories;

import com.company.dataanalytics.domain.aggregates.report.Report;
import com.company.dataanalytics.domain.valueobjects.GenerationStatus;
import com.company.dataanalytics.domain.valueobjects.ReportId;
import com.company.dataanalytics.domain.valueobjects.TemplateId;
import com.company.dataanalytics.domain.valueobjects.UserId;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for Report aggregate
 */
public interface IReportRepository {
    
    /**
     * Find report by ID
     */
    Optional<Report> findById(ReportId reportId);
    
    /**
     * Find all reports generated from a specific template
     */
    List<Report> findByTemplate(TemplateId templateId);
    
    /**
     * Find all reports generated by a specific user
     */
    List<Report> findByGeneratedBy(UserId userId);
    
    /**
     * Find reports by generation status
     */
    List<Report> findByStatus(GenerationStatus status);
    
    /**
     * Find reports generated within a date range
     */
    List<Report> findByGenerationTimestampBetween(Instant startDate, Instant endDate);
    
    /**
     * Find all reports with pagination
     */
    List<Report> findAll(int page, int size);
    
    /**
     * Save report
     */
    void save(Report report);
    
    /**
     * Delete report
     */
    void delete(ReportId reportId);
    
    /**
     * Count total reports
     */
    long count();
    
    /**
     * Count reports by status
     */
    long countByStatus(GenerationStatus status);
    
    /**
     * Find pending reports (for processing)
     */
    List<Report> findPendingReports();
    
    /**
     * Find failed reports for retry
     */
    List<Report> findFailedReports();
}